<?php

namespace DoctrineProxy\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Medicine extends \Entities\Medicine implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entities\\Medicine' . "\0" . 'id_medicine', '' . "\0" . 'Entities\\Medicine' . "\0" . 'cis', '' . "\0" . 'Entities\\Medicine' . "\0" . 'name', '' . "\0" . 'Entities\\Medicine' . "\0" . 'administration', '' . "\0" . 'Entities\\Medicine' . "\0" . 'autorisation', '' . "\0" . 'Entities\\Medicine' . "\0" . 'procedure', '' . "\0" . 'Entities\\Medicine' . "\0" . 'status', '' . "\0" . 'Entities\\Medicine' . "\0" . 'date_autorisation', '' . "\0" . 'Entities\\Medicine' . "\0" . 'availability', '' . "\0" . 'Entities\\Medicine' . "\0" . 'autorisation_number', '' . "\0" . 'Entities\\Medicine' . "\0" . 'brand', '' . "\0" . 'Entities\\Medicine' . "\0" . 'security', '' . "\0" . 'Entities\\Medicine' . "\0" . 'date_created', '' . "\0" . 'Entities\\Medicine' . "\0" . 'date_updated');
        }

        return array('__isInitialized__', '' . "\0" . 'Entities\\Medicine' . "\0" . 'id_medicine', '' . "\0" . 'Entities\\Medicine' . "\0" . 'cis', '' . "\0" . 'Entities\\Medicine' . "\0" . 'name', '' . "\0" . 'Entities\\Medicine' . "\0" . 'administration', '' . "\0" . 'Entities\\Medicine' . "\0" . 'autorisation', '' . "\0" . 'Entities\\Medicine' . "\0" . 'procedure', '' . "\0" . 'Entities\\Medicine' . "\0" . 'status', '' . "\0" . 'Entities\\Medicine' . "\0" . 'date_autorisation', '' . "\0" . 'Entities\\Medicine' . "\0" . 'availability', '' . "\0" . 'Entities\\Medicine' . "\0" . 'autorisation_number', '' . "\0" . 'Entities\\Medicine' . "\0" . 'brand', '' . "\0" . 'Entities\\Medicine' . "\0" . 'security', '' . "\0" . 'Entities\\Medicine' . "\0" . 'date_created', '' . "\0" . 'Entities\\Medicine' . "\0" . 'date_updated');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Medicine $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdMedicine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMedicine', array());

        return parent::getIdMedicine();
    }

    /**
     * {@inheritDoc}
     */
    public function setCis($cis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCis', array($cis));

        return parent::setCis($cis);
    }

    /**
     * {@inheritDoc}
     */
    public function getCis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCis', array());

        return parent::getCis();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministration($administration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministration', array($administration));

        return parent::setAdministration($administration);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministration', array());

        return parent::getAdministration();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutorisation($autorisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutorisation', array($autorisation));

        return parent::setAutorisation($autorisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutorisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutorisation', array());

        return parent::getAutorisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcedure($procedure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcedure', array($procedure));

        return parent::setProcedure($procedure);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcedure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcedure', array());

        return parent::getProcedure();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAutorisation($dateAutorisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAutorisation', array($dateAutorisation));

        return parent::setDateAutorisation($dateAutorisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAutorisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAutorisation', array());

        return parent::getDateAutorisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailability($availability)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailability', array($availability));

        return parent::setAvailability($availability);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailability()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailability', array());

        return parent::getAvailability();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutorisationNumber($autorisationNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutorisationNumber', array($autorisationNumber));

        return parent::setAutorisationNumber($autorisationNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutorisationNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutorisationNumber', array());

        return parent::getAutorisationNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand($brand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', array($brand));

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', array());

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecurity($security)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecurity', array($security));

        return parent::setSecurity($security);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecurity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecurity', array());

        return parent::getSecurity();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', array($dateCreated));

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', array());

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpdated($dateUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpdated', array($dateUpdated));

        return parent::setDateUpdated($dateUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpdated', array());

        return parent::getDateUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

}
